name: Build and Deploy Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          backend/package-lock.json

    - name: Install and Build Frontend
      run: |
        npm install --force
        npm run build

    - name: Install Backend Dependencies
      working-directory: backend
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        npm install --force
        npm run build  # This is just a placeholder script since backend doesn't need building

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.frontend
        push: ${{ github.event_name == 'push' }}
        tags: |
          ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/frontend:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/frontend:latest
        cache-to: type=inline

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: backend
        file: backend/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          ghcr.io/${{ github.repository }}/backend:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/backend:latest
        cache-to: type=inline

    - name: Start Backend Server
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      working-directory: backend
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        npm start
        # Note: The server will run in the background automatically
        # GitHub Actions will keep this step running until the workflow completes
